version: '2'
services:
  application:
    build:
      context: ./docker/application
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links:
      - postgresql
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  postgresql:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
