version: '2'
services:
  application:
    build:
      context: ./docker/application
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links:
      - postgresql

  postgresql:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
